"use client";

import { FormEvent, useState } from "react";
import { LoaderCircle, X } from "lucide-react";
import { api } from "@/lib/api";
import type { AuthTokens } from "@/types";

export function AuthDialog({ mode, onClose, onAuthenticated }: { mode: "login" | "register"; onClose: () => void; onAuthenticated: (tokens: AuthTokens) => void }) {
  const [currentMode, setCurrentMode] = useState(mode); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); try { if (currentMode === "register") await api.register({ full_name: String(data.get("name")), email: String(data.get("email")), password: String(data.get("password")) }); const tokens = await api.login({ email: String(data.get("email")), password: String(data.get("password")) }); onAuthenticated(tokens); } catch (caught) { setError((caught as Error).message); } finally { setLoading(false); } }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#01090d]/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={`${currentMode} to KeyVault AI`}><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-white/20 bg-[#0a202a] p-7 shadow-2xl"><div className="mb-6 flex items-start justify-between"><div><p className="gradient-title text-2xl font-black">KeyVault-AI</p><h2 className="mt-1 text-xl font-bold">{currentMode === "login" ? "Unlock your vault" : "Create your vault"}</h2></div><button type="button" onClick={onClose} aria-label="Close" className="rounded-lg p-2 hover:bg-white/10"><X/></button></div>{currentMode === "register" && <label>Full name<input name="name" required className="field" /></label>}<label>Email<input name="email" type="email" required autoComplete="email" className="field" /></label><label>Password<input name="password" type="password" required minLength={10} autoComplete={currentMode === "login" ? "current-password" : "new-password"} className="field" /></label>{error && <p role="alert" className="mt-4 rounded-lg bg-rose-500/15 p-3 text-sm text-rose-200">{error}</p>}<button disabled={loading} className="mt-6 flex w-full justify-center rounded-xl bg-gradient-to-r from-fuchsia-500 to-indigo-500 px-5 py-3 font-bold disabled:opacity-60">{loading ? <LoaderCircle className="animate-spin"/> : currentMode === "login" ? "Unlock Vault" : "Register Now"}</button><p className="mt-4 text-center text-sm text-slate-300">{currentMode === "login" ? "New here?" : "Already have an account?"} <button type="button" onClick={() => { setCurrentMode(currentMode === "login" ? "register" : "login"); setError(""); }} className="font-bold text-pink-300">{currentMode === "login" ? "Create account" : "Login"}</button></p></form></div>;
}
